name: otp_user_consent_api
description: Android implementation of OTP autofill with using User Concent API
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  surf_lint_rules:
    path: ../surf_lint_rules

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.surfstudio.otp_user_consent_api
        pluginClass: OTPUsertConsentAPI
      ios:
        pluginClass: OTPUsertConsentAPI

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: true
  path: otp_user_consent_api
  separate_repo_url:
  hostUrl: