name: surf_network
version: "0.1.0-dev.0"
description: Network implementation for Flutter
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/surf_network"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.0.0-nullsafety.0
  dio: ^3.0.10
  http: ^0.12.2
  http_parser: ^3.1.4
  rxdart: ^0.26.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: surf_network
  separate_repo_url:
  hostUrl:
