name: network_cache
version: "0.0.1-dev.1"
description: Caching http requests.
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/network_cache"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.0
  surf_lint_rules: "^0.0.1-dev.0"
  flutter_test:
    sdk: flutter
  surf_storage: "^0.0.1-dev.0"
  surf_network: "^0.0.1-dev.0"

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: network_cache
  separate_repo_url:
  hostUrl:
