name: relation
version: "0.1.0-dev.0"
description: the stream representation of the relations of the entities and widget utilities
homepage: "https://github.com/surfstudio/relation"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3
  rxdart: ^0.26.0-nullsafety.1
  surf_lint_rules: ^0.0.2-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: relation
  separate_repo_url: "https://github.com/surfstudio/relation"
  hostUrl:
