name: video_subtitle
description: A new Flutter plugin.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.9.0
  video_player: '>=0.10.11+1 <2.0.0'
  srt_parser: ^1.1.0+5
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: ru.surfstudio.video_subtitle
        pluginClass: VideoSubtitlePlugin
      ios:
        pluginClass: VideoSubtitlePlugin
