name: in_app_rate
version: "0.0.1-dev.1"
description: "Plugin use in-app review and App Store Review"
publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules:
    git:
      url: "https://gitlab.com/surfstudio/public/flutter-standard.git"
      path: packages/surf_lint_rules

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: ru.surfstudio.in_app_rate
        pluginClass: InAppRatePlugin
      ios:
        pluginClass: InAppRatePlugin

custom:
  is_stable: false
  unstable_version:
  is_plugin: true
  path: in_app_rate
  separate_repo_url:
  hostUrl:
