name: in_app_rate
version: "0.1.0-dev.0"
description: "Plugin use in-app review and App Store Review"
publish_to: none

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  surf_lint_rules: ^0.0.2-dev.2

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: ru.surfstudio.in_app_rate
        pluginClass: InAppRatePlugin
      ios:
        pluginClass: InAppRatePlugin

custom:
  is_stable: false
  unstable_version:
  is_plugin: true
  path: in_app_rate
  separate_repo_url:
  hostUrl:
