name: mwwm
description: Reflection of widget in a single entity
version: 0.0.2
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #внутренние библиотеки
  injector:
    git:
      url: https://bitbucket.org/surfstudio/flutter-standard.git
      ref: dev
      path: injector

  #rx
  rxdart: 0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.8.0+1

flutter:

custom:
  is_stable: false
  unstable_version: 0
  is_plugin: false
  path: mwwm
  separate_repo_url:
  hostUrl:
