name: surf_util
version: "0.0.1-dev.9"
description: Common classes and util.
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/surf_util"

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: ^0.0.2-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0-0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: surf_util
  separate_repo_url:
  hostUrl:
