name: example
description: Example of using event filter.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  event_filter:
    path: ..

  #rx
  rxdart: ^0.26.0-nullsafety.1

  #surfstudio
  surf_injector:
    git:
      url: https://github.com/surfstudio/SurfGear
      path: packages/surf_injector
      ref: feature/surf_injector_null_safety
  surf_mwwm:
    git:
      url: https://github.com/surfstudio/SurfGear
      path: packages/surf_mwwm
      ref: feature/surf_mwwm_null_safety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
