name: ci
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pubspec_parse: 0.1.5
  yaml: 2.2.0
  pubspec_yaml: ^1.0.0+1
  yamlicious: ^0.1.0
  shell: ^1.0.1
  path: ^1.6.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.11.1
  mockito: ^4.1.1
