name: text_field_validation
version: "1.0.0-dev.4"
description: Validating text fields
repository: "https://github.com/surfstudio/SurfGear/tree/dev/packages/text_field_validation"
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  surf_lint_rules: "^0.0.1-dev.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.6.0 <3.0.0"

flutter:

custom:
  is_stable: false
  unstable_version:
  is_plugin: false
  path: text_field_validation
  hostUrl:
  separate_repo_url:
